name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build release Docker image
        run: docker build -f release.Dockerfile . -t coqbot
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: coqbot
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
